### ISSUE TITLE
Should restrict required permissions to stackoverflow.com 

### ISSUE THREAD

**Issue by ruffin--** [lets-hack-stuff/stackoverflow-upvote-first#5]
When I attempt to install on Chrome from the Store, it requires permission to run on every URL.

That's obviously too broad. It should be [restricted](https://stackoverflow.com/a/10504438/1028230) to stackoverflow.com (or at least stackexchange sites).

Current requirement:
<img width="482" alt="allWebsites" src="https://user-images.githubusercontent.com/5659878/104979890-53924b00-59d3-11eb-9fff-c3510a5081f5.png">

**Comment by jossef** [comment]
I'll fix this. Thanks.

I thought setting the following rules will do the trick:
https://github.com/lets-hack-stuff/stackoverflow-upvote-first/blob/master/src/manifest.json#L26
